coisa = input('digite qualquer coisa')
print('o tipo primitivo desse valor é ', type(coisa))
print('é numero? ', coisa.isnumeric())
print('é letra? ', coisa.isalpha())
print('é alfanumerico? ', coisa.isalpha())
print('é só espaço? '), coisa.isspace()
print('da para imprimir? ', coisa.isprintable())
print('é um digito? ', coisa.isdigit())
print('é só espaço? '), coisa.isspace()
